### ISSUE TITLE
Timestamp of Outgoing Packets

### ISSUE THREAD

**Issue by AqsaKashaf** [libmoon/libmoon#112]
Hi, 

I want to record the timestamp of outgoing packets. Do you think there is a way to do that with MoonGen?

**Comment by emmericp** [comment]
Call `buf:enableTimestamps()` followed by `txQueue:getTimestamp(timeoutInMicros)` after sending it. IIRC this works on most packets on most Intel NICs. Some NICs may restrict this to packets that look like PTP and some drivers may not support it at all.

See also the implementation of our latency measurement: https://github.com/libmoon/libmoon/blob/master/lua/timestamping.lua#L65

**Comment by AqsaKashaf** [comment]
buf:enableTimestamps() appear to be unsupported in device.lua
