### ISSUE TITLE
IcmpTask takes control of RxQueue causing other functions to wait forever.

### ISSUE THREAD

**Issue by ashokkumarprajapati** [libmoon/libmoon#24]
In my master function i started Icmp Task followed by counter slave:

`icmp.startIcmpTask({txQueue= txQueue, rxQueue = rxQueue, ips = args.ip})
mg.startTask("counterSlave", rxQueue, args)
`

counter function is as below:
`
function counterSlave(rxQueue, txQueue, args)
    
    local bufs = memory.bufArray(128)
    ctr = stats:newPktRxCounter("Port " .. args.dstPort, "plain")
    while mg.running() do
        local rx = rxQueue:tryRecvIdle(bufs, 1) 
        for i = 1, rx do
            local buf = bufs[i]
            local pkt = buf:getUdpPacket()
            local port = pkt.udp:getDstPort()
            ctr:countPacket(buf)
        end
        ctr:update(1)
        bufs:freeAll()
        if (runtime:running() == false) then
            arp.stopArpTask()
            mg.stop()
        end
    end
    ctr:finalize()
`

My receiver counter is not getting any packets due to ICMP Task. if i comment IcmpTask then it gets working.

**Comment by emmericp** [comment]
You cannot use the same queue from multiple tasks at the same time, this isn't supported by DPDK.

You can use a device-statistics based counter like the stats task if you only want statistics.
