### ISSUE TITLE
Add a way to set the logging level for libmoon internal code

### ISSUE THREAD

**Issue by pudelkoM** [libmoon/libmoon#33]
There is currently no way to disable logging messages originating from internal libmoon code.
Running the following script still prints warnings to stdout:
```
local log = require "log"
log:setLevel("ERROR")
local lm = require "libmoon"

function master()
end
```

Output:
```
[WARN]  malloc() allocates objects >= 1 MiB from LuaJIT memory space.
[WARN]  Install libjemalloc if you encounter out of memory errors.
```

Expected output:
```
```

This is problematic in automated work flows, where adherence to certain output format, such as csv, is expected.

**Comment by emmericp** [comment]
Sorry, won't fix.

1. too annoying since the memory lib needs to be loaded before the user script
2. DPDK generates some uncontrollable spam anyways
