### ISSUE TITLE
Cisco enic support

### ISSUE THREAD

**Issue by trodery** [libmoon/libmoon#40]
Hello,

I noticed that the necessary driver setup code for the Cisco enic dpdk driver was missing from libmoon. Is this a deliberate decision? If not, I'd like to potentially submit a pull request to include it. My very limited testing of this driver has shown that I am unable to exceed roughly 1.5Mpps regardless of packet size when providing PCI pass through of a Cisco VIC 1280 from a Cisco UCS/B-series blade server via VMware ESXi 6.5 hypervisor. Any insight into the above is greatly appreciated.

**Comment by emmericp** [comment]
Not deliberate, no. I just don't have access to any Cisco hardware.
The driver-specific setup code will hopefully be gone soon (was caused by a linker problem).

The limit sounds like some artificially enforced? Are you passing through a VF or a PF?
