### ISSUE TITLE
a problem of sending and receiving UDP by pkts

### ISSUE THREAD

**Issue by qwe131829** [libmoon/libmoon#70]
Why the experiment sends UDP  from a server using pktgen, and when the MAC address is deliberately miswritten, the traffic is displayed through the dump-pkts in another server？it can also be received by dump-pkts when the ip is wrong?I don't know why it happened. Is it a broadcast？

**Comment by emmericp** [comment]
Packet dumpers usually operate in promisc mode and don't care about the mac address. The routing between your servers is unrelated.
