### ISSUE TITLE
How to use the thread of libmoon

### ISSUE THREAD

**Issue by qwe131829** [libmoon/libmoon#71]
In the experiment, code of redis storage  was added to dump-pkts.lua. But after monitoring, it is found that the key of data storage is far less than the number of packets. I have counted the number of receiving packets, and found that in the process of receiving and parsing, the packet loss rate is far greater than the number of packets. See libmoon support multithreading, but do not know how to use?
local bufs = memory.bufArray()
        local num =1
	while lm.running() do
		local rx = queue:tryRecv(bufs, 10)
		local batchTime = lm.getTime()
		for i = 1, rx do
			local buf = bufs[i]
--			if(next(buf) ~= nil)then
			if filter(buf:getBytes(), buf:getSize()) then
				print(buf:getBytes())
                                print(buf:getSize())

				if writer then
					print(buf:getBytes())
					print(buf:getSize())
					writer:writeBuf(batchTime, buf, snapLen)
					captureCtr:countPacket(buf) 
                                       
				else
                              local mem =  buf:getUdpPacket()
                               num=num+1
                             print(num)
  
                           client:hmset('UDP'..num,'src_port',mem.udp:getSrcPort(),'dst_port',mem.udp:getDstPort(),'length',mem.udp:getLength(),'Checksum',mem.udp:getChecksum(),'src_ip',mem.ip4:getSrcString(),'dst_ip',mem.ip4:getDstString(),'src_mac',mem.eth:getSrcString(),'dst_mac',mem.eth:getDstString())                         
                           
                            -- buf:dump()
                                
                                     
			--end
				end

**Comment by emmericp** [comment]
the dump-pkts.lua already comes with multi-threading. See https://github.com/libmoon/libmoon/blob/master/examples/inter-task-communication.lua for general multi-threading concepts
