### ISSUE TITLE
negative TCP sequence numbers

### ISSUE THREAD

**Issue by thomas-schultz** [libmoon/libmoon#72]
getSeqNumber() and getAckNumber() as well as the get*String() methods will return negative values.
Additionally the comment should say 32 instead of 8 bit integer.

**Comment by emmericp** [comment]
Sorry, that was caused by the byte swapping. We've usually handled these things as opaque values (or passed them on to C code as uint32 which automatically "fixes" this also)

I've added an explicit conversion
