### ISSUE TITLE
 Interception 

### ISSUE THREAD

**Issue by Lukaiwe** [libmoon/libmoon#73]
Hello, I 'd like to ask you how to intercept a message.

**Comment by emmericp** [comment]
care to elaborate?

**Comment by Lukaiwe** [comment]
How do I verify that a valid packet was sent with libmoon?  thanks

**Comment by emmericp** [comment]
i can't help you unless you describe what exactly you are trying to achieve and why it's not working as expected

**Comment by cremlscent** [comment]
I want to use libmoon to send a DNS request message to the DNS server, but the package I constructed has not been answered, I don't know what went wrong.

**Comment by emmericp** [comment]
Try calling :dump() on your buf (the buf, not the packet). But it looks like your problem is on a higher layer, so maybe standard tools on the server side might be better suited.
