### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [libmoon/libmoon#76]
I am a designer who loves to help open sources. I designed a logo for you. I can give you a gift if you want to use it. What do you think?

![libmoon](https://user-images.githubusercontent.com/41051393/42958059-281c519e-8b8d-11e8-86e9-1928f318b1ff.jpg)

**Comment by EaseTheWorld** [comment]
It seems 'l' is lower-case intentionally.
I'm not a designer but, may I suggest override crescent and full moon in 'oo'?
I don't know how.. just an idea.

**Comment by emmericp** [comment]
Thanks, but we are currently not looking for a logo to brand libmoon.

We do have a logo for MoonGen, but we don't really use that quite often (except on slides and posters): [mg-logo.pdf](https://github.com/libmoon/libmoon/files/2249447/mg-logo.pdf)
