### ISSUE TITLE
Decapsulation requires header offset

### ISSUE THREAD

**Issue by EaseTheWorld** [libmoon/libmoon#79]
In Moongen vxlan decapsulation example,
encapsulationLen(= 14 + 20 + 8 + 8) is constant but what if some header has variable size options?
I tried (pkt.payload.uint8 - buf:getBytes) but it doesn't include variable len either.
It would be useful if libmoon provide header offset considering variable len.

**Comment by EaseTheWorld** [comment]
Oh, pkt:get() can handle variable sizes headers.
then add offset for each header in packetResolveLastHeader() will do?
I wanted to add myself but I have not fully understood packet.lua yet(and very new to lua).

**Comment by emmericp** [comment]
@scholzd can you upload a preprint/draft of the relevant paper somewhere and link it?

the main problem with pkt:get() is that it is slow. If you want to have it in fast, then you'll have to figure out the variable lengths yourself/have a guard on non-default sized headers and cast them to an instance of the appropriate protocol stack

**Comment by EaseTheWorld** [comment]
ok then I'll try without pkt:get().
To handle 2.5 layer like vlan layer do I always have to make 2 stacks?
eth          ip4 udp tunnel...and
eth vlan ip4 udp tunnel...
Any example for this?
What is the easiest way to get tunnel header offset?

**Comment by emmericp** [comment]
paper draft with examples: https://www.net.in.tum.de/fileadmin/bibtex/publications/papers/scholz_protocol_stack.pdf

Yes, you'll need two stacks if you also want to handle vlan tagged packets. VLAN tags are annoying, so offload them if you can. Sure, offloading isn't always available, especially if handling the inner packet in a tunnel.... I've implemented Code like this (internal stuff, not public). It basically works by checking the type and casting it to the correct stack; the two stack objects can then be handled by the same code if you used the same name for the fields.
