### ISSUE TITLE
Modification of received data leads to lower forwarding rate.

### ISSUE THREAD

**Issue by qwe131829** [libmoon/libmoon#80]
In filter.lua , the received data can be forwarded directly. I modified the IP address in the received packet and sent it, but caused the sending rate to drop rapidly. The rate of sending only 1.3 ~1.4Mpps. The previous idea was to store the data in redis and then regenerate the packet to implement tampering and forwarding. But it leads to a lot of data loss, you said that the string operation will greatly affect the performance, so I want to modify some data and then forward directly, but the performance is still not high. 
1) If you do not use a string, how to tamper with the IP address. In a hot loop, the effect of strings is very large.
2) libmoon reduces the certain packet rate to find a balance point with storage, so that the packet loss rate is appropriately reduced.
What is the reason and what is the solution or good idea?
	local rxBufs = memory.bufArray()
	local txBufs = memory.bufArray()
	while lm.running() do
		local rx = rxQueue:recv(rxBufs)
		local j = 0
		for i = 1, rx do
			local buf = --
			if filter(rxBufs[i]) then
				rxBufs[i]:free()		
			else
  			   	local mem = buf:getUdpPacket()
                                 mem.ip4:setDstString("202.119.236.5")
                                j = j + 1
				txBufs[j] = rxBufs[i]
			end
		end
		txQueue:sendN(txBufs, j)
	end
end

**Comment by emmericp** [comment]
String operations are slow. See any of the l3-* examples on handling IPs efficiently.
