### ISSUE TITLE
Error on running dump-pkts.lua example

### ISSUE THREAD

**Issue by tinajohnson** [libmoon/libmoon#89]
I am facing an error when I try to run the dump-pkts.lua example using the command: 
`sudo ./build/libmoon examples/dump-pkts.lua 0`
where 0 is the device id. I do get the following log when running the example before it terminates with error:
`[INFO]  Found 1 usable devices:
Device 0: 00:25:90:69:CA:C8 (Intel Corporation 82574L Gigabit Network Connection)`

The error is:
`/home/tina/libmoon/lua/device.lua:196: Could not configure device 0: error Invalid argument`

Are there any other arguments that need to be passed to run the example? Or does the error have anything to do with the device?

**Comment by emmericp** [comment]
82574L is not a great NIC, it probably doesn‘t support one of our default parameters. It‘s > 10 years old.

I recommend getting a better NIC, i.e. a i350 or better.

**Comment by emmericp** [comment]
There's really only one option on which this NIC is likely failing: `dropEnable` which we set to true by default.

Try adding `dropEnable = false` to the `device.config`, that should fix it.

But you really should get a different NIC, you'll also run into other problems with the 82574L

**Comment by tinajohnson** [comment]
Hi,

We tried disabling dropEnable (and also, did the unbind and bind again) but it still says the device is down. So, we have ordered another NIC. While we wait, is there any other small tweaks or tricks we could try? 

Thank you for your prompt replies!

**Comment by emmericp** [comment]
Then it's probably related to queue size or maybe rss (even if set to just 1, it probably tries to enable it?)? Anyways, there isn't really a point in using any DPDK application with that NIC.

**Comment by tinajohnson** [comment]
We have installed a brand new NIC on our machine (Intel(R) Ethernet Converged Network Adapter XXV710-DA2 (2x25G)). Even now while we try to run the same error shows up:

`pulkit@ixmon:~/FlowScope$ sudo ./libmoon/build/libmoon lua/flowscope.lua examples/liveStatistician.lua 0
[INFO]  Initializing DPDK. This will take a few seconds...
EAL: Detected 24 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:158b net_i40e
EAL: PCI device 0000:04:00.1 on NUMA socket 0
EAL:   probe driver: 8086:158b net_i40e
[INFO]  Found 1 usable devices:
   Device 0: 3C:FD:FE:CC:97:B4 (unknown NIC (PCI ID 8086:158b))
[INFO]  checkExpiry: function: 0x40528dd0
[INFO]  checkInitializer: function: 0x40528d90
[INFO]  extractFlowKey: function: 0x40526e88
[INFO]  stateType: struct live_flow_state
[INFO]  logLevel: WARN
[INFO]  defaultState: table: 0x40526f60
[INFO]  checkFinalizer: function: 0x40528be8
[INFO]  flowKeys: table: 0x40529078
[INFO]  checkInterval: 5
[INFO]  handlePacket: function: 0x40528c88
[INFO]  {struct ipv4_5tuple -> struct live_flow_state}: cdata<struct hmapk16v64 *>: 0x012f7730
[INFO]  {struct ipv6_5tuple -> struct live_flow_state}: cdata<struct hmapk64v64 *>: 0x012f7980
[INFO]  direct mode
[INFO]  Waiting for devices to come up...
[INFO]  Key buffer size: 64
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[INFO]  [Checker]: Started
Top flows over sliding 5s window:
#    bps    pps    Flow
Active flows 0, cumulative packets 0 [0.00/s], cumulative bytes 0 [0.00/s], took 0.00s
[INFO]  [Checker]: Done, took 0.000122s, flows 0/0/0 [purged/kept/total]
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[ERROR] Device 0 (3C:FD:FE:CC:97:B4) is DOWN: 0 MBit/s
[INFO]  0 devices are up.
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[INFO]  [Checker]: Started
Top flows over sliding 5s window:
#    bps    pps    Flow
Active flows 0, cumulative packets 0 [0.00/s], cumulative bytes 0 [0.00/s], took 0.00s
[INFO]  [Checker]: Done, took 0.000053s, flows 0/0/0 [purged/kept/total]
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)
[Analyzer] RX: 0.00 Mpps, 0 Mbit/s (0 Mbit/s with framing)`

We were trying the livestatician.lua from Flowscope examples but we are running into the same dpdk errors. Do you have any pointers for us? Appreciate your help, Thanks!
