### ISSUE TITLE
Newer DPDK

### ISSUE THREAD

**Issue by sonman** [libmoon/libmoon#91]
Please update to a more recent DPDK. 
DPDK will not compile with newer Mellanox driver.

**Comment by emmericp** [comment]
Can you please provide more details? Driver version, kernel version, distribution?

**Comment by sonman** [comment]
Driver version: MLNX_OFED_SRC-debian-4.5-1.0.1.0
kernel version: 4.13.0-36-generic
distribution: Ubuntu 16.04

**Comment by emmericp** [comment]
That should work. Which NIC are you using?

**Comment by sonman** [comment]
DPDK 17.11.4 compiles with this mellanox version.
DPDK 17.11.3 not.

**Comment by sonman** [comment]
ConnectX-5

**Comment by sonman** [comment]
Which changes have to be done to integrate at least DPDK 17.11.4 ?
Maybe I can support ...

**Comment by emmericp** [comment]
current master is on the latest dpdk release
